---
- name: ensure required packages are installed
  apt:
    name: "{{ themes_required_packages }}"
    state: present
  become: true

- name: ensure theme directory exists
  file:
    path: "{{ themes_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true

- name: ensure icons directory exists
  file:
    path: "{{ icons_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true

- name: clone rtl themes from git
  git:
    repo: "{{ rtl_git_repository }}"
    dest: "/tmp/{{ item.directory }}"
    depth: "1"
    version: "{{ item.version }}"
    force: true
  loop: "{{ rtl_themes }}"
  notify:
    - copy all icon directories into place
    - copy all desktop theme directories into place
