---
- name: ensure required packages are installed
  apt:
    name: "{{ apt_packages }}"
    state: present
  vars:
    apt_packages: "{{ themes_required_packages }}"

- name: ensure theme directory exists
  file:
    path: "{{ themes_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: ensure icons directory exists
  file:
    path: "{{ icons_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: create temporary directory
  tempfile:
    state: directory
    suffix: temp
  register: temp_dir

- name: clone arc darkest repo
  git:
    repo: "{{ rtl_repo }}"
    dest: "{{ temp_dir }}"
    depth: "1"
    version: Arc-Darkest-COLORS-Complete-Desktop
  notify:
    - copy files to theme directory
    - copy files to icons directory
    - remove temporary directory

- name: install lxappearance to manage themes
  apt:
    name: lxappearance
    state: present
  when: lxappearance
