---
- name: copy files to theme directory
  copy:
    src: "{{ temp_dir }}/"
    dest: "{{ themes_path }}"
    remote_src: true
    mode: 0755
    owner: root
    group: root
  register: copy_theme_data

- name: copy files to icons directory
  copy:
    src: "{{ temp_dir }}/"
    dest: "{{ icons_path }}"
    remote_src: true
    mode: 0755
    owner: root
    group: root

- name: remove temporary directory
  file:
    path: "{{ temp_dir }}"
    state: absent
  when: temp_dir.path is defined
