---
- name: copy all icon directories into place
  command: find . -maxdepth 1 -not -path './[Numix]*' -not -path './[Suru]*' -type d \( -iname '*suru*' -o -iname '*numix*' \) -exec mv -t {{ icons_path }} "{}" \;
  args:
    chdir: /tmp/{{ item.directory }}
  loop: "{{ rtl_themes }}"
  become: true

- name: copy all desktop theme directories into place
  command: find . -mindepth 1 -maxdepth 1 -type d ! -name .git -exec mv -t {{ themes_path }} "{}" \;
  args:
    chdir: /tmp/{{ item.directory }}
  loop: "{{ rtl_themes }}"
  become: true
