---
- name: Converge
  hosts: all
  vars:
    rtl_themes:
      - directory: rtl88-arc_darkest_complete
        version: Arc-Darkest-COLORS-Complete-Desktop
      - directory: rtl88-nord_black_frost
        version: Nord-Black-Frost

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    - name: install git
      apt:
        name: git
        state: present

  tasks:
    - name: "Include ansible-role-arc_darkest_theme"
      include_role:
        name: "ansible-role-arc_darkest_theme"
