---
- name: Verify
  hosts: all

  tasks:
    - name: Collect package facts.
      package_facts:
        manager: "auto"

    - name: Verify gtk2-engines-murrine is installed.
      assert:
        that:
          - "'gtk2-engines-murrine' in ansible_facts.packages"
        success_msg: "gtk2-engines-murrine is installed."
        fail_msg: "gtk2-engines-murrine is not installed."

    - name: Find /usr/share/themes/rtl88-arc_darkest directory.
      find:
        path: /usr/share/themes/rtl88-arc_darkest
        file_type: directory
      register: themes_found

    - name: Find /usr/share/icons/rtl88-arc_darkest directory.
      find:
        path: /usr/share/icons/rtl88-arc_darkest
        file_type: directory
      register: icons_found

    - name: Verify arc_darkest themes directory exists.
      assert:
        that:
          - "themes_found.matched > 0"
        success_msg: "themes dir found and is not empty"
        fail_msg: "themes dir found, but is empty"

    - name: Verify arc_darkest icons directory exists.
      assert:
        that:
          - "icons_found.matched > 0"
        success_msg: "icons dir found and is not empty"
        fail_msg: "icons dir found, but is empty"
